apiVersion: v1
kind: Pod
metadata:
  name: helloizer
spec:
  containers:
    - image: gcr.io/cloud-appstate-fall22/helloizer:v1
      name: helloizer
      ports:
        - containerPort: 8080
          name: http
          protocol: TCP
